### PR TITLE
allow the portalled component to receive updated input

### PR DESCRIPTION
**Pull request by noisyscanner**
# Problem
If a component that is rendering a portal re-renders, and passes new input to the portal, this never gets propagated to the portalled component, so it never receives the new input and does not re-render

# Solution
Have a wrapper component sitting between `Portal` and the portalled component that holds the input in state, and expose a query `SetInput` that the `Portal` can use to update it.

### CODE REVIEW

**Comment by flip111** [comment]
I just hit this bug today, such a coincidence you posted yesterday ^^ Thank you for working on this.

Is a wrapper component necessary? Why can't the input be passed directly?

**Comment by flip111** [comment]
To answer my own question: because `Halogen.Aff.Driver.runUI` [makes the input inaccessible](https://github.com/purescript-halogen/purescript-halogen/blob/v7.0.0/src/Halogen/Aff/Driver.purs#L120-L124) which is only available in the [internals](https://github.com/purescript-halogen/purescript-halogen/blob/v7.0.0/src/Halogen/Aff/Driver/State.purs#L146)

**Comment by thomashoneyman** [comment]
@flip111 Does this PR fix your issue? If so I'm happy to merge it.

**Comment by flip111** [comment]
Yes it works great, please merge it.

**Comment by thomashoneyman** [comment]
Thanks @noisyscanner.

**Comment by noisyscanner** [comment]
Cheers! <3

**Pull request merged**
